function scaffoldRobot(className, parentClass, description)
% SCAFFOLDROBOT Generate a new robot class file under +robot/
%   scaffoldRobot(className, parentClass, description)
%
%   className      - Name of the new class (e.g., 'Hexapod')
%   parentClass    - Parent class name (e.g., 'GroundRobot')
%   description    - Brief description string (one line)
%
% Example:
%   scaffoldRobot('Hexapod', 'GroundRobot', '6-legged walking robot')

    if nargin < 3
        error('Usage: scaffoldRobot(className, parentClass, description)');
    end

    filename = fullfile(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))), ...
                        '+robot', [className, '.m']);

    if exist(filename, 'file')
        error('File already exists: %s', filename);
    end

    template = sprintf([...
        'classdef %s < %s\n' ...
        '    properties\n' ...
        '    end\n' ...
        '\n' ...
        '    methods\n' ...
        '        function obj = %s(params)\n' ...
        '            obj@%s(params);\n' ...
        '            %s\n' ...
        '        end\n' ...
        '\n' ...
        '        function move(obj, direction, amount)\n' ...
        '            % direction: robot.Direction enum\n' ...
        '            % amount: scalar magnitude\n' ...
        '            % Implement vehicle-specific dynamics here.\n' ...
        '        end\n' ...
        '\n' ...
        '        function geom = buildGeometry(obj)\n' ...
        '            % Return vertices and edges for wireframe.\n' ...
        '        end\n' ...
        '    end\n' ...
        'end\n'], ...
        className, parentClass, className, parentClass, ...
        ['% ' description]);

    fid = fopen(filename, 'w');
    fprintf(fid, '%s', template);
    fclose(fid);
    fprintf('Created: %s\n', filename);
end
